api:
  id: "123456" # replace with real id once added to api manager
  #API Configurations
  name: "${project.name}"
  version: "${api.version}"
  path: api/v1/*
  
http:
  private:
    port: "8091"
  
httpsRequest:
  host: "sm-api-dev.acme.com"
  port: "443"
  path:
    sqlpath: "/finance/inbound/oracle-erp-sql-sys-api/v1/oracle/runsql"
    getPath: "/finance/outbound/finance-parkinglot-sys-api/v1/parkinglot"
    eventsPatchPath: "/finance-parkinglot-sys-api/v1/events"
  reconnection:
    frequency: "2000"
    attempts: "2" 
  clientId: "replace with actual values"
  clientSecret: "replace with actual values"    


# Azure SQL (Parking System API) - override sql.password in CloudHub/Anypoint per environment
sql:
  driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  host: "parking-sql-dev-73b543.database.windows.net"
  port: "1433"
  database: "parking-db"
  user: "![C6zRGMw2nG9f+jTwIV2xeQ==]"
  password: "![oVbk6geC6Ji21yNfEK6LZ0FwQIdaMp2MSWAuOEBkwAw=]"
